// AUTO-GENERATED by build.mjs — do not edit by hand. Run `npm run build`.
export const photos = [
  {
    "src": "cindy-family.jpg",
    "caption": "Best Grandparents EVER."
  },
  {
    "src": "Cindy-her-girls.jpg",
    "caption": "Thank you for always taking good care of your girls."
  },
  {
    "src": "cindy-boys.jpg",
    "caption": "Thank you for always taking good care of your boys."
  },
  {
    "src": "cindy-grandma.jpg",
    "caption": "Thank you for always loving my children."
  },
  {
    "src": "cindy-granma-sommer.png",
    "caption": "This girl adores her Grandma Cindy."
  },
  {
    "src": "Cindy-celebrating-family.jpg",
    "caption": "Graduations are better with Opa and Grandma Cindy."
  },
  {
    "src": "family-bonds.jpg",
    "caption": "The Pridgen family bonds are strong!"
  },
  {
    "src": "cindy-glen.jpg",
    "caption": "Thank you for always being there for me."
  },
  {
    "src": "cindy-dad-michelle.jpeg",
    "caption": "I love this pic."
  }
];
